### ISSUE TITLE
[FEAT] 이슈 등록 기능 구현 

### ISSUE THREAD

**Issue by sharpie1330** [codesquad-masters2024-team09/issue-tracker#1]
## 🔥 Feature Issue
이슈 등록 기능을 구현합니다.
member dummy data를 사용해서 임시로 이슈를 등록하고 저장하는 기능을 먼저 구현합니다.

해당 기능은 팀원 모두가 code with me를 통해 함께 작업합니다.

## ✅ TODO
 - [x] ERD 기반 Entity 클래스 초기화
 - [x] schema.sql 작성
 - [x] mysql driver 연결(local)
 - [x] 이슈 등록 기능 구현
 - [x] 테스트 코드 작성

**Comment by sharpie1330** [comment]
IssueControllerTest에서 이슈 등록 테스트 실패로 해당 테스트코드 수정을 위한 이슈 추가
