### ISSUE TITLE
[FEAT] Label 도메인 기능 구현

### ISSUE THREAD

**Issue by sharpie1330** [codesquad-masters2024-team09/issue-tracker#14]
## 🔥 Feature Issue
Label 도메인 기능을 구현합니다.

## ✅ TODO
 - [x] 레이블 등록 구현
 - [x] 레이블 목록 조회 구현
 - [x] 레이블 수정 구현
 - [x] 레이블 삭제 구현
 - [x] 테스트 코드 작성
