### ISSUE TITLE
[FEAT] 댓글 CRUD 기능 구현

### ISSUE THREAD

**Issue by jellyyelly** [codesquad-masters2024-team09/issue-tracker#15]
## 🔥 Feature Issue
댓글의 단순 CRUD 기능을 구현합니다.

- 이슈와 댓글은 1:N 관계이다
- 데이터베이스의 댓글 테이블(COMMENT)은 댓글의 순서를 보장하는 comment_seq 컬럼을 갖는다

## ✅ TODO
 - [x] ERD 댓글 부분 수정
 - [x] 댓글 엔터티 작성
   - [x] 이슈와 댓글 1:N 연관관계 매핑
 - [x] 댓글을 저장할 수 있다
   - [x] 저장에 성공하면 `200 ok 코드`와 `댓글의 아이디`를 JSON 으로 응답한다 
 - [x] 댓글 목록을 조회할 수 있다
   - [x] 이슈 세부 정보를 조회하면 연관관계 매핑에 의해 전체 댓글이 자동으로 조회된다 (추후 페이징 처리)
 - [x] 댓글을 수정할 수 있다
   - [x] 수정에 성공하면 `200 ok 코드`와 `수정한 댓글의 내용`을 JSON 으로 응답한다
 - [x] 댓글을 삭제할 수 있다
   - [x] 삭제에 성공하면 `200 ok 코드`와 `삭제된 댓글 아이디`를 JSON 으로 응답한다
 - [x] 댓글을 검증할 수 있다
   - [x] 댓글의 제목은 빈 값일 수 없다
   - [x] 댓글의 내용은 2000자를 초과할 수 없다
