### ISSUE TITLE
[FEAT] 마일스톤 기능 구현

### ISSUE THREAD

**Issue by seedspirit** [codesquad-masters2024-team09/issue-tracker#16]
## 🔥 Feature Issue
- 마일스톤의 단순 CRUD 기능을 구현합니다
- Delete의 경우 Hard Deletion으로 구현합니다

## ✅ TODO
- [x] 마일스톤 엔터티 작성
- [x] 마일스톤 목록 조회 API
   - [x] 마일스톤의 상태별로 나누어 조회되도록 구현합니다
   - [x] 현재 단계에서 Pagination은 고려하지 않습니다
- [x] 마일스톤 생성 API
   - [ ] 생성에 성공할 경우 201 created를 반환
- [ ] 마일스톤 수정 API
  - [ ] 수정에 성공할 경우 200 ok와 수정된 내용을 JSON으로 응답
- [x] 마일스톤 삭제 API
  - [ ] 삭제에 성공하면 200 ok를 반환
- [ ] 마일스톤의 상태별 갯수를 반환하는 API
  - [ ] 열린 마일스톤 갯수를 반환하는 API
  - [ ] 닫힌 마일스톤 갯수를 반환하는 API
