### ISSUE TITLE
[FEAT] 연관관계 매핑

### ISSUE THREAD

**Issue by jellyyelly** [codesquad-masters2024-team09/issue-tracker#23]
### 연관관계 매핑 작업
- Issue - Comment : One-to-Many (이미 구현 되어있음)
- Issue - Label : Many-to-Many
- Issue - Milestone : Many-to-One

### 테스트 코드 수정
#19 해결하기

## ✅ TODO
- [x] Issue - Comment : `List<Comment>`필드 에 Comment 객체를 추가할 수 있는 `addComment()` 메서드 추가
- [x] Issue - Label : 레이블을 1개 또는 여러 개를 추가할 수 있는 `addLabel()`, `addLabels()` 메서드와 레이블을 제거할 수 있는 `deleteLabel()` 메서드 추가
  - [x] Issue - IssueLabel : One-to-Many 연관관계 매핑
  - [x] IssueLabel - Label : Many-to-One 연관관계 매핑
- [x] Issue - Milestone : 마일스톤을 지정하거나 제거할 수 있는 `assignMilestone()`, `deleteMilestone()` 메서드 추가
- [x] #19 해결
