### ISSUE TITLE
[FEAT] 연관관계 매핑된 도메인들에 대한 Controller 메서드 구현

### ISSUE THREAD

**Issue by sharpie1330** [codesquad-masters2024-team09/issue-tracker#26]
## 🔥 Feature Issue
#23 에서 작업한 연관관계 매핑 작업에 대한 Controller 메서드 부재로 해당 부분에 대해 구현합니다.

## ✅ TODO
 - [x] 이슈에 레이블 지정 컨트롤러 메서드 구현 
 - [x] 이슈에 마일스톤 지정 컨트롤러 메서드 구현
 - [x] 테스트 코드 작성
