### ISSUE TITLE
[FEAT] 엔터티 연관관계 매핑 관련 컨트롤러, 서비스 수정

### ISSUE THREAD

**Issue by jellyyelly** [codesquad-masters2024-team09/issue-tracker#32]
## 🔥 Feature Issue
- 컨트롤러에서 서비스 계층을 호출할 때 웹 계층에서 사용하는 DTO를 전달하지 않도록 수정합니다
- 서비스 계층에서 검증하는 로직 중 일부를 DTO 에게 직접 시키고, DTO와의 의존성을 낮춥니다
- 잘못 추가된 Comment 스키마 일부를 수정합니다

## ✅ TODO
 - [ ] 컨트롤러에서 DTO를 서비스에게 전달하는 부분 제거
 - [ ] 서비스 계층에서 DTO 의존성 제거
 - [ ] DTO 내부 검증 로직 추가
 - [ ] COMMENT 테이블 스키마 수정 (schema.sql)
