### ISSUE TITLE
[FEAT] 이슈 목록조회 기능 및 상태변경 로직 구현

### ISSUE THREAD

**Issue by sharpie1330** [codesquad-masters2024-team09/issue-tracker#44]
## 🔥 Feature Issue
이슈 목록 조회 기능을 개발합니다.

## ✅ TODO
 - [x] IssuePreviewResponse, IssueListResponse 추가 및 응답 객체로 사용
 - [x] 이슈 목록 조회 기능 구현
 - [x] 이슈 열기, 닫기 기능 구현 -> 한 번에 가능하도록
 - [ ] 이슈 목록 페이징 구현
 - [x] 이슈 목록 필터링 구현
 - [ ] 테스트 코드 작성
