### ISSUE TITLE
[FEAT] 이슈 상세 조회 기능 구현

### ISSUE THREAD

**Issue by seedspirit** [codesquad-masters2024-team09/issue-tracker#5]
## 🔥 Feature Issue
- 저장된 이슈의 상세 내용을 볼 수 있는 기능을 구현합니다
- 현재 단계에서는 코멘트 기능은 구현하지 않습니다

## ✅ TODO
 - [x] 이슈 상세 조회 화면 만들기
 - [x] 이슈 엔터티의 식별자를 바탕으로 db에서 해당 이슈 조회하기
 - [x] 조회 성공 시 200응답과 함께 필요한 정보를 반환
