### ISSUE TITLE
[FIX] PR#49 누락 파일 추가, 타임리프 제거, 레이블 svelte store 디렉토리 변경

### ISSUE THREAD

**Issue by jellyyelly** [codesquad-masters2024-team09/issue-tracker#55]
## 🔥 Fix Issue
feat/#37-fix 브랜치에 누락된 파일을 추가하기 위해 해당 이슈를 열었습니다

### 상세 설명
- PR#49 에 이슈 조회 관련 누락된 파일 추가
- 프로젝트에서 타임리프 관련 내용 제거
- 스벨트 Label 스토어 파일(label.js) 폴더 이동 (store -> stores)

## ✅ TODO
- [x] PR#49 에 이슈 조회 관련 누락된 파일 추가
- [x] 프로젝트에서 타임리프 관련 내용 제거
- [x] 스벨트 Label 스토어 파일(label.js) 폴더 이동
