### ISSUE TITLE
[FEAT] 마일스톤 진행률 계산

### ISSUE THREAD

**Issue by seedspirit** [codesquad-masters2024-team09/issue-tracker#58]
## 🔥 Feature Issue
- 이슈 상세 조회 시 마일스톤의 진행률도 함께 조회
- 마일스톤 조회 시 마일스톤 진행률, 열린 이슈 개수, 닫힌 이슈 개수, 열려있는 지 여부도 함꼐 응답하도록 구현

## ✅ TODO
 - [ ] 이슈 상세 조회 시 마일스톤의 진행률을 계산할 수 있는 api 작성
 - [ ] 이슈 상세 조회 시 마일스톤의 진행률도 함께 조회
 - [ ] 마일스톤 조회 시 마일스톤 진행률, 열린 이슈 개수, 닫힌 이슈 개수, 열려있는 지 여부도 함꼐 응답하도록 구현
