### ISSUE TITLE
[FEAT] 담당자 관련 기능 구현 및 프론트 api 연결 작업

### ISSUE THREAD

**Issue by sharpie1330** [codesquad-masters2024-team09/issue-tracker#69]
## 🔥 Feature Issue
- 담당자 할당, 해제 등 멤버와 관련된 기능을 구현합니다.
- 로그인, 회원가입 등 멤버와 관련된 프론트와 api를 연동합니다.

## ✅ TODO
 - [x] 로그인, 회원가입 api 연동
 - [x] 담당자 할당, 해제
 - [x] 회원탈퇴 기능 구현
 - [x] 토큰 관련 api 연동
 - [ ] 테스트 코드 작성
