### ISSUE TITLE
[FEAT] 이슈 생성 로직 추가 구현 및 보완

### ISSUE THREAD

**Issue by sharpie1330** [codesquad-masters2024-team09/issue-tracker#7]
## 🔥 Feature Issue
기존에 간략히 구현되었던 이슈 생성 로직을 보완하고 추가적인 기능을 더 구현합니다.

## ✅ TODO
 - [ ] 검증 로직 구현
 - [ ] 이슈 등록 예외처리 코드 작성
 - [ ] 테스트코드 추가 구현
