### ISSUE TITLE
[FIX] 마일스톤 수정기능 오류 해결 및 댓글, 이슈 로그인 여부에 따라 다르게 보여지도록 수정, 아이디 유효성 검증 로직 추가

### ISSUE THREAD

**Issue by sharpie1330** [codesquad-masters2024-team09/issue-tracker#75]
## 🔥 Fix Issue
- 마일스톤 편집이 putMapping으로 변경되며 발생하는 문제 해결
- 본인만 댓글 편집 가능하도록 하는 부분 해결
- 회원가입 시 아이디 유효성 검증 로직 추가

## ✅ TODO
 - [x] 마일스톤 편집 기능 수정
 - [x] 댓글 편집 기능 수정
 - [x] 로그인한 유저만 이슈 편집, 삭제 가능하도록 수정
 - [x] 이슈 열기 닫기 기능 연결 
 - [x] 아이디 유효성 검증
