### ISSUE TITLE
[FIX] 사이드 바 팝업창 버그 수정

### ISSUE THREAD

**Issue by jellyyelly** [codesquad-masters2024-team09/issue-tracker#76]
## 🔥 Fix Issue
사이드 바 팝업창 관련 버그를 수정합니다

### 상세 설명
- 사이드 바 팝업창을 눌렀을 때 담당자, 레이블, 마일스톤 등 1개도 존재하지 않을 떄 '{xxx}가 존재하지 않습니다' 가 나오지 않는 문제 수정
- 담당자 선택이 정상작동하지 않는 문제 수정
- 이슈 생성 시 선택된 담당자들이 표시되도록 수정

## ✅ TODO
 - [x] 사이드 바 팝업창 컴포넌트에 배열 개수 확인으로 변경
 - [x] 담당자 클릭 시 전달하는 매개변수 수정
 - [x] 이슈 생성 시 선택한 담당자들 함께 등록되도록 수정
