### ISSUE TITLE
[FEAT] 프로필 팝업 메뉴

### ISSUE THREAD

**Issue by jellyyelly** [codesquad-masters2024-team09/issue-tracker#79]
## 🔥 Feature Issue
프로필 이미지 클릭 시 로그아웃와 회원탈퇴를 할 수 있는 팝업창을 구현합니다

## ✅ TODO
 - [ ] 프로필을 누르면 팝업창이 나온다
 - [ ] 팝업창에 로그아웃 버튼을 누르면 로그아웃이 된다
 - [ ] 팝업창에 회원탈퇴 버튼을 누르면 회원탈퇴가 된다
