### ISSUE TITLE
[FEAT] 이슈 삭제 기능 구현

### ISSUE THREAD

**Issue by seedspirit** [codesquad-masters2024-team09/issue-tracker#8]
## 🔥 Feature Issue
- 특정 이슈를 삭제하는 기능을 구현합니다
- 현재 단계에서는 hard delete 방식으로 구현합니다

## ✅ TODO
 - [ ] 이슈 엔터티의 식별자(issueId)를 바탕으로 해당 이슈를 db에서 삭제하기
 - [ ] 삭제가 성공하였을 경우 
   - [ ] 302 상태 코드, 리다이렉션 경로는 '/'로 응답을 보낸다
   - [ ] 브라우저에서는 '이슈가 삭제 되었습니다' 라는 alert를 보낸 후 응답받은 경로로 redirection 하게 한다
