### ISSUE TITLE
[FEAT] 이슈 조회 필터 기능 (#65)

### ISSUE THREAD

**Issue by jellyyelly** [codesquad-masters2024-team09/issue-tracker#84]
## 🔥 Feature Issue
#65 작업에 이어서 리팩토링 대신 새로운 스토어를 만드는 방향으로 작업합니다

## ✅ TODO
 - [ ] 필터 버튼을 누르면 팝업창이 표시된다
 - [ ] 팝업창의 아이템을 클릭하면 검색창에 입력되며, 즉시 api를 호출한다
 - [ ] 필터링된 결과를 화면에 다시 로드한다
